#!/usr/bin/env bash
# Resolve VERSION_NAME / VERSION_CODE from tag and optionally write android/version.properties.
# Usage: source scripts/android-version-from-tag.sh v1.0.1
#    or: scripts/android-version-from-tag.sh v1.0.1 [--write]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
raw="${1:-}"
write_props=0
[[ "${2:-}" == "--write" ]] && write_props=1

if [[ -z "$raw" ]]; then
  echo "usage: android-version-from-tag.sh <v1.0.1> [--write]" >&2
  exit 1
fi

tag="${raw#refs/tags/}"
tag="${tag#v}"

if [[ ! "$tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "error: expected semver tag like v1.0.1, got: $raw" >&2
  exit 1
fi

VERSION_NAME="$tag"
core="${tag%%[-+]*}"
IFS='.' read -r major minor patch <<< "$core"
VERSION_CODE=$(( major * 10000 + minor * 100 + patch ))

export VERSION_NAME
export VERSION_CODE

if [[ "$write_props" -eq 1 ]]; then
  cat > "$ROOT/android/version.properties" <<EOF
# Generated by scripts/android-version-from-tag.sh — commit before release build.
versionName=${VERSION_NAME}
versionCode=${VERSION_CODE}
EOF
  echo "wrote android/version.properties (versionName=$VERSION_NAME versionCode=$VERSION_CODE)"
fi

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  printf 'export VERSION_NAME=%q\n' "$VERSION_NAME"
  printf 'export VERSION_CODE=%q\n' "$VERSION_CODE"
fi
